name: Compilar Winlator Ludashi Mali

on:
  workflow_dispatch: # Permite disparar la compilación manualmente desde la pestaña Actions

jobs:
  build-apk:
    name: Compilar APK Híbrido (Mali + Vortek)
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar Código Fuente Completo de tu Rama
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: 2. Configurar Entorno de Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: 3. Otorgar Permisos de Ejecución al Compilador Local Gradle
        run: chmod +x gradlew

      - name: 4. Ejecutar Forja y Compilación del APK (Modo Depuración)
        run: ./gradlew assembleDebug --no-daemon

      - name: 5. Subir APK Fusionado como Artefacto Descargable de GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Winlator-Ludashi-Mali-Vortek-APK
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7
