name: 🚀 Compilador de Winlator Ludashi Desde Mi Fork

on:
  workflow_dispatch: # Activa el botón manual "Run workflow" en la pestaña Actions

jobs:
  build-ludashi-3-1:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el Código Fuente Original de la Rama ludashi-3.1
        uses: actions/checkout@v4
        with:
          ref: ludashi-3.1
          submodules: 'recursive' # Clona los submódulos tal como vienen de fábrica
          fetch-depth: 0

      - name: 2. Configurar Entorno de Java (JDK 17 Oficial)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 3. Configurar Android SDK Nativo del Servidor
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_ENV
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null || true

      - name: 4. Conceder Permisos de Ejecución al Compilador Gradle
        run: chmod +x gradlew

      - name: 5. Ejecutar Compilación Pura y Nativa de Fábrica (Variante 3.1)
        run: |
          # 🚀 ENLAZADOR GRÁFICO BLINDADO 3.1:
          # Inyectamos en las banderas del compilador la ruta de las cabeceras de Vulkan y Mesa
          # para que Clang localice 'vk_context.h' en las subcarpetas del proyecto aunque el submódulo falle.
          export CFLAGS="-Wno-error -Wno-incompatible-pointer-types-discards-qualifiers -I/home/runner/work/Winlator-Ludashi/Winlator-Ludashi/app/src/main/cpp/winlator"
          export CXXFLAGS="-Wno-error"
          ./gradlew assembleDebug --no-daemon

      - name: 6. Localizar el APK Resultante de la Forja
        run: |
          echo "🔍 Buscando la ruta exacta del instalador:"
          find app/build/outputs -name "*.apk" || echo "No se encontró ningún APK"

      - name: 7. Subir APK Original 3.1 como Artefacto Descargable
        uses: actions/upload-artifact@v4
        with:
          name: Winlator-Ludashi-3.1-Pure-Build
          path: "**/*.apk"
          retention-days: 7
